# -----------------------------------------------------------------------------
# Monitoring Stage: Configure Gatus Dashboard on Site-1
# -----------------------------------------------------------------------------
#
# This stage configures AWS site-1 as the main Gatus dashboard that monitors:
# - Self health check
# - AWS site-2 Gatus health endpoint
# - AWS site-2 private VM connectivity (ICMP ping + TCP port 22)
# - GCP Gatus health endpoint
# - GCP private VM connectivity (ICMP ping + TCP port 22)

# Read site terraform state to get VM details
data "terraform_remote_state" "site" {
  backend = "local"
  config = {
    path = "${path.module}/../site/terraform.tfstate"
  }
}

locals {
  # Extract data from site state
  aws_sites        = data.terraform_remote_state.site.outputs.aws_sites
  aws_site_config  = data.terraform_remote_state.site.outputs.aws_site_config
  gcp_vm           = data.terraform_remote_state.site.outputs.gcp_vm
  gcp_vpc_name     = data.terraform_remote_state.site.outputs.gcp_vm_vpc_name
  gcp_region       = data.terraform_remote_state.site.outputs.gcp_vpc_info.region
  ssh_key_file     = data.terraform_remote_state.site.outputs.aws_ssh_private_key_file

  # Dashboard configuration
  dashboard_site_name = var.dashboard_site
  dashboard_site      = local.aws_sites[local.dashboard_site_name]
  dashboard_ip        = local.dashboard_site.vm.public_vm_public_ip
  dashboard_region    = local.aws_site_config[local.dashboard_site_name].region

  # Build list of monitored sites (excluding dashboard site)
  other_aws_sites = {
    for name, site in local.aws_sites : name => site
    if name != local.dashboard_site_name
  }

  # Generate Gatus config YAML
  gatus_config = <<-YAML
# Gatus Dashboard Configuration
# Auto-generated by monitoring terraform stage

endpoints:
  # Self health check
  - name: "aws-${local.dashboard_site_name}-${local.dashboard_region}"
    group: local
    url: "http://localhost:${var.gatus_port}/health"
    interval: 1s
    conditions:
      - "[STATUS] == 200"

  # Dashboard site private VM ICMP
  - name: "aws-${local.dashboard_site_name}-${local.dashboard_region}-icmp"
    group: local
    url: "icmp://${local.dashboard_site.vm.private_vm_private_ip}"
    interval: 1s
    conditions:
      - "[CONNECTED] == true"

%{for name, site in local.other_aws_sites~}
  # AWS ${name} monitoring
  - name: "aws-${name}-${local.aws_site_config[name].region}-gatus"
    group: aws
    url: "http://${site.vm.public_vm_public_ip}:${var.gatus_port}/health"
    interval: 1s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 5000"

  - name: "aws-${name}-${local.aws_site_config[name].region}-icmp"
    group: aws
    url: "icmp://${site.vm.private_vm_private_ip}"
    interval: 1s
    conditions:
      - "[CONNECTED] == true"

  - name: "aws-${name}-${local.aws_site_config[name].region}-ssh"
    group: aws
    url: "tcp://${site.vm.private_vm_private_ip}:22"
    interval: 1s
    conditions:
      - "[CONNECTED] == true"

%{endfor~}
  # GCP monitoring
  - name: "gcp-${local.gcp_vpc_name}-${local.gcp_region}-gatus"
    group: gcp
    url: "http://${local.gcp_vm.public_vm_public_ip}:${var.gatus_port}/health"
    interval: 1s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 5000"

  - name: "gcp-${local.gcp_vpc_name}-${local.gcp_region}-icmp"
    group: gcp
    url: "icmp://${local.gcp_vm.private_vm_private_ip}"
    interval: 1s
    conditions:
      - "[CONNECTED] == true"

  - name: "gcp-${local.gcp_vpc_name}-${local.gcp_region}-ssh"
    group: gcp
    url: "tcp://${local.gcp_vm.private_vm_private_ip}:22"
    interval: 1s
    conditions:
      - "[CONNECTED] == true"
YAML
}

# Write config to local file for debugging
resource "local_file" "gatus_config" {
  content  = local.gatus_config
  filename = "${path.module}/generated_gatus_config.yaml"
}

# Update Gatus config on dashboard site
resource "null_resource" "configure_gatus" {
  triggers = {
    config_hash = sha256(local.gatus_config)
  }

  connection {
    type        = "ssh"
    host        = local.dashboard_ip
    user        = var.ssh_username
    private_key = file(local.ssh_key_file)
    timeout     = "2m"
  }

  # Upload new Gatus config
  provisioner "file" {
    content     = local.gatus_config
    destination = "/tmp/gatus_config.yaml"
  }

  # Apply config and restart Gatus container
  provisioner "remote-exec" {
    inline = [
      "sudo cp /tmp/gatus_config.yaml /etc/gatus/config.yaml",
      "sudo docker restart gatus",
      "sleep 5",
      "echo 'Gatus config updated and container restarted'",
    ]
  }
}
